### ISSUE TITLE
path kit

### ISSUE THREAD

**Issue by lmaron-g** [2suggar/lem_in#7]
typedef struct	s_stack
{
	int			lenght;
	int			*stack;
}				t_stack;

typedef struct	s_pathkit
{
	int			lenght;
	t_stack		**stack;
}				t_pathkit;

t_pathkit		*np_init()
{
	t_pathkit	*kit;

	int		a;

	a = 0;
	if (!(kit = (t_pathkit*)malloc(sizeof(t_pathkit) * /* count of ways */)))
		error();
}

**Comment by slaveareyou** [comment]
typedef struct	s_stack
{
int	lenght;
int	*stack;
}	t_stack;

typedef struct	s_pathkit
{
int	lenght;
t_stack	*stack;
}	t_pathkit;

t_pathkit	*np_init()
{
t_pathkit	*kit;

int		a;

a = 0;
if (!(kit = (t_pathkit*)malloc(sizeof(t_pathkit) * /* count of ways */)))
	error();
}
